services:
  zookeeper:
    build:
      context: zookeeper/
      args:
        ZKP_VERSION: ${ZKP_VERSION}
    volumes:
      - zookeeper_data:/opt/zookeeper/data
    restart: always
    container_name: zookeeper
    ports:
      - 2181:2181
    networks:
      - obs
  kafka:
    build:
      context: kafka/
      args:
        KAFKA_VERSION: ${KAFKA_VERSION}
    volumes:
      - kafka_data:/kafka
    restart: always
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: kafka.lab
      # HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:9094
      KAFKA_ADVERTISED_LISTENERS:  INTERNAL://kafka:9092,OUTSIDE://kafka.lab:9094
    ports:
      - 9092:9092
      - 9094:9094
    networks:
      - obs
    depends_on:
      - zookeeper
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local